FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv==0.12.5

COPY pyproject.toml uv.lock ./

RUN uv sync --locked

COPY app ./app
COPY tests ./tests

CMD ["uv", "run", "pytest", "-v"]